import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  metadataBase: new URL("https://bizysite.in"),
  title: "AI Policy | Bizy Site",
  description: "How Bizy Site uses artificial intelligence responsibly in design, development, and content creation.",
  alternates: {
    canonical: "/ai-policy",
  },
};

export default function AiPolicy() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": "https://bizysite.in/ai-policy/#webpage",
    "url": "https://bizysite.in/ai-policy",
    "name": "AI Policy"
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      
      <Header />

      <section className="service-hero" style={{ padding: "100px 0 40px 0" }}>
        <div className="container service-hero-content">
          <span className="section-tag light" style={{ color: "rgba(255,255,255,0.85)" }}>Legal</span>
          <h1 className="service-hero-title">Responsible AI Policy</h1>
          <p className="service-hero-sub">
            How we integrate artificial intelligence tools responsibly to deliver high-converting, search-optimized web experiences.
          </p>
        </div>
      </section>

      <section className="section-padding" style={{ background: "var(--white)" }}>
        <div className="container" style={{ maxWidth: "800px", color: "var(--text)", fontSize: "15px", lineHeight: "1.8" }}>
          
          <h3 style={{ fontSize: "20px", color: "var(--navy)", fontWeight: "800", marginTop: "24px", marginBottom: "12px" }}>1. Our Stance on Generative AI</h3>
          <p style={{ color: "var(--text-mid)", marginBottom: "20px" }}>
            Generative AI is a powerful assistant, not a replacement for human expertise. We use advanced LLMs and design tools to accelerate coding, run initial audit benchmarks, and check structural SEO metadata. However, all final wireframes, copy adjustments, and strategic decisions are made and reviewed by our senior human experts.
          </p>

          <h3 style={{ fontSize: "20px", color: "var(--navy)", fontWeight: "800", marginTop: "24px", marginBottom: "12px" }}>2. Content Integrity & Code Verification</h3>
          <p style={{ color: "var(--text-mid)", marginBottom: "12px" }}>
            - **No Raw Copypaste:** We never publish raw AI-generated text. Every line of website copy is tailored, edited, and outcome-reviewed by our team to maintain conversion integrity.
          </p>
          <p style={{ color: "var(--text-mid)", marginBottom: "20px" }}>
            - **Code Standards:** Any utility scripts or code blocks generated by AI tools are rigorously tested, linted, and reviewed for security, performance, and cross-browser responsiveness.
          </p>

          <h3 style={{ fontSize: "20px", color: "var(--navy)", fontWeight: "800", marginTop: "24px", marginBottom: "12px" }}>3. Data Privacy & Model Safety</h3>
          <p style={{ color: "var(--text-mid)", marginBottom: "20px" }}>
            We do not input sensitive customer details, proprietary source code, or private commercial files into public, unencrypted AI models. Your business data remains safe and protected under strict security baselines.
          </p>

          <h3 style={{ fontSize: "20px", color: "var(--navy)", fontWeight: "800", marginTop: "24px", marginBottom: "12px" }}>4. Optimizing for AI Engines (GEO/AEO)</h3>
          <p style={{ color: "var(--text-mid)", marginBottom: "20px" }}>
            As part of our commitment to modern search trends, we build websites optimized for AI answer engine indexing (like ChatGPT Search, Gemini, Perplexity, and Google AI Overviews). This involves clear content hierarchies, structured schemas, and clean markdown tags.
          </p>

          <h3 style={{ fontSize: "20px", color: "var(--navy)", fontWeight: "800", marginTop: "24px", marginBottom: "12px" }}>5. Contact Us</h3>
          <p style={{ color: "var(--text-mid)", marginBottom: "20px" }}>
            If you have questions regarding our AI guidelines, please email us at <a href="mailto:info@bizysite.com" style={{ color: "var(--teal)", fontWeight: "700" }}>info@bizysite.com</a>.
          </p>

        </div>
      </section>

      <Footer />
    </>
  );
}
